package com.benjamin.easygrader.util;

public enum Destination {
  CREATE_USER,
  REMOVE_USER,
  ADD_COURSE,
  REMOVE_COURSE,
  ADD_ASSIGNMENT,
  REMOVE_ASSIGNMENT,
  MODIFY_ASSIGNMENT,
  GRADE_ASSIGNMENT,
  FINALIZE_GRADES;
}
